name: Auto Contributer
on:
  workflow_dispatch:
  schedule:
    - cron: "55 7 * * *"
jobs:
  contribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run contribute
